apiVersion: v1
kind: LimitRange
metadata:
  name: task-container-limit
spec:
  limits:
  - max:
      cpu: '800m'
      memory: '1Gi'
    min:
      cpu: '50m'
      memory: '99Mi'
    default:
      cpu: '700m'
      memory: '900Mi'
    defaultRequest:
      cpu: '110m'
      memory: '111Mi'
    type: Container
