apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline
imagePullSecrets:
- name: reg-cred
secrets:
- name: ssh-key
- name: reg-cred
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-triggers
rules:
# EventListeners need to be able to fetch all namespaced resources
- apiGroups: ['triggers.tekton.dev']
  resources: ['eventlisteners', 'triggerbindings', 'triggertemplates', 'triggers']
  verbs: ['get', 'list', 'watch']
- apiGroups: ['']
  # secrets are only needed for GitHub/GitLab interceptors
  # configmaps is needed for updating logging config
  resources: ['configmaps', 'secrets']
  verbs: ['get', 'list', 'watch']
  # Permissions to create resources in associated TriggerTemplates
- apiGroups: ['tekton.dev']
  resources: ['pipelineruns', 'pipelineresources', 'taskruns']
  verbs: ['create']
- apiGroups: ['']
  resources: ['serviceaccounts']
  verbs: ['impersonate']
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  resourceNames: ['tekton-triggers']
  verbs: ['use']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-triggers
  namespace: default
subjects:
- kind: ServiceAccount
  name: pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-triggers
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-triggers
rules:
# EventListeners need to be able to fetch any clustertriggerbindings
- apiGroups: ['triggers.tekton.dev']
  resources: ['clustertriggerbindings']
  verbs: ['get', 'list', 'watch']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-triggers
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipeline
  namespace: default
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: default
roleRef:
  kind: ClusterRole
  name: edit  # Required for rollout
  apiGroup: rbac.authorization.k8s.io
