apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline
imagePullSecrets:
- name: reg-cred
secrets:
- name: ssh-key
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipeline
  namespace: default
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: default
roleRef:
  kind: ClusterRole
  name: edit  # Required for rollout
  apiGroup: rbac.authorization.k8s.io
