apiVersion: v1
kind: Secret
metadata:
  name: ssh-key
  annotations:
    tekton.dev/git-0: github.com
type: kubernetes.io/ssh-auth
data:
  # cat ~/.ssh/id_rsa_github | base64
  ssh-privatekey: |-
  <SSH_KEY_PATH>
  # cat ~/.ssh/known_hosts | base64
  known_hosts: |-
  <SSH_KNOWN_HOST_PATH>
---
# kubectl create secret generic reg-cred \
#  --from-file=.dockerconfigjson=<DOCKER_CFG_PATH> \
#  --type=kubernetes.io/dockerconfigjson
#
# This secret has to be dockerconfigjson, otherwise `git-clone` Task won't be able to fetch repositories
apiVersion: v1
kind: Secret
metadata:
  name: reg-cred
  annotations:
    tekton.dev/docker-0: 'https://docker.io'
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <DOCKER_CONFIG_PATH>
---
apiVersion: v1
kind: Secret
metadata:
  name: slack-webhook
type: Opaque
stringData:
  #  url: https://hooks.slack.com/services/...
  url: <SLACK_WEBHOOK>
