apiVersion: v1
kind: Secret
metadata:
  name: ssh-key
  annotations:
    tekton.dev/git-0: github.com
type: kubernetes.io/ssh-auth
data:
  # cat ~/.ssh/id_rsa_github | base64
  ssh-privatekey: |-
  <SSH_KEY_PATH>
  # cat ~/.ssh/known_hosts | base64
  known_hosts: |-
  <SSH_KNOWN_HOST_PATH>
---
apiVersion: v1
kind: Secret
metadata:
  name: reg-cred
  annotations:
    tekton.dev/docker-0: https://docker.io
type: kubernetes.io/basic-auth
stringData:
  username: <DOCKER_USERNAME>
  password: <DOCKER_PASSWORD>
---
apiVersion: v1
kind: Secret
metadata:
  name: slack-webhook
type: Opaque
stringData:
#  url: https://hooks.slack.com/services/...
  url: <SLACK_WEBHOOK>
