apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: cron-listener
spec:
  serviceAccountName: pipeline
  triggers:
    - name: cron-trigger
      bindings:
        - ref: cron-binding
      template:
        ref: cron-template
