apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: cron-template
spec:
  params:
    - name: HOST
      description: Database host.
    - name: DATABASE
      description: Database name.
    - name: DEST
      description: Backup destination (file path).
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: job-
        # Alternatives:
        # name: job-$(uid)
        labels:
          tekton.dev/pipeline: cron-job
      spec:
        params:
          - name: HOST
            value: $(tt.params.HOST)
          - name: DATABASE
            value: $(tt.params.DATABASE)
          - name: DEST
            value: $(tt.params.DEST)
        pipelineRef:
          name: database-backup
        workspaces:
          - name: backup
            # https://github.com/tektoncd/pipeline/blob/master/docs/workspaces.md#persistentvolumeclaim
            persistentVolumeClaim:
              claimName: backup
