apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: healthcheck
spec:
  params:
    - name: name
      description: Deployment name.
    - name: namespace
      default: default
  steps:
    - name: wait
      image: 'bitnami/kubectl:1.20.2'
      command:
        - kubectl
        - wait
        - --for=condition=available
        - --timeout=600s
        - deployment/$(params.name)
        - -n
        - $(params.namespace)