# To only create ClusterTask without testing resources:
# kubectl apply -f tasks/dive.yaml -l type=core
#
# To only create testing resources without ClusterTask:
# kubectl apply -f tasks/dive.yaml -l type=test
apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  annotations:
  name: dive
  labels:
    type: core
spec:
  params:
    - name: IMAGE
      description: Name (reference) of the image to analyze.
  steps:
    - image: wagoodman/dive:latest
      name: dive
      env:
        - name: CI
          value: 'true'
      command:
        - dive
        - $(params.IMAGE)
      volumeMounts:
        - mountPath: /var/run/
          name: dind-socket
  sidecars:
    - image: docker:18.05-dind
      name: server
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/lib/docker
          name: dind-storage
        - mountPath: /var/run/
          name: dind-socket
  volumes:
    - name: dind-storage
      emptyDir: {}
    - name: dind-socket
      emptyDir: {}
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: dive
  namespace: default
  labels:
    type: test
spec:
  taskRef:
    name: dive
    kind: ClusterTask
  params:
    - name: IMAGE
      value: martinheinz/python-project-blueprint:0.0.6-12-g1232208-dirty
