# To only create ClusterTask without testing resources:
# kubectl apply -f tasks/get-application-name.yaml -l type=core
#
# To only create testing resources without ClusterTask:
# kubectl apply -f tasks/get-application-name.yaml -l type=test
apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  annotations:
  name: get-application-name
  labels:
    type: core
spec:
  params:
    - name: repository-url
      type: string
    - name: mapping-file
      type: string
  steps:
    - name: get-application-name
      image: mikefarah/yq
      script: |
        #!/usr/bin/env sh
        set -xe

        yq e '."$(params.repository-url)"' /config/$(params.mapping-file) | tr -d '\012\015' > /tekton/results/application-name
  results:
    - name: application-name
  workspaces:
    - name: config
      mountPath: /config
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: get-application-name
  namespace: default
  labels:
    type: test
spec:
  taskRef:
    name: get-application-name
    kind: ClusterTask
  params:
    - name: repository-url
      value: 'git@github.com:kelseyhightower/nocode.git'
    - name: mapping-file
      value: repo-app-mapping.yaml
  workspaces:
    - name: config
      configmap:
        name: repo-app-mapping
---
# Expected result:
# kubectl get tr get-application-name -o json | jq .status.taskResults
# [
#   {
#     "name": "application-name",
#     "value": "nocode"
#   }
# ]