# To only create Pipeline without testing resources:
# kubectl apply -f pipelines/cron.yaml -l type=core
#
# To only create testing resources without Pipeline:
# kubectl apply -f pipelines/cron.yaml -l type=test
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: database-backup
  labels:
    type: core
spec:
  workspaces:
    - name: backup
  params:
    - name: HOST
      type: string
    - name: DATABASE
      type: string
    - name: DEST
      type: string
  tasks:
    - name: pg-dump
      taskRef:
        name: pg-dump
        kind: ClusterTask
      params:
        - name: HOST
          value: $(params.HOST)
        - name: DATABASE
          value: $(params.DATABASE)
        - name: DEST
          value: $(params.DEST)
      workspaces:
        - name: backup
          workspace: backup
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: database-backup
  namespace: default
  labels:
    type: test
spec:
  params:
    - name: HOST
      value: 'postgres.default.svc.cluster.local'
    - name: DATABASE
      value: postgres
    - name: DEST
      value: 'test.bak'
  pipelineRef:
    name: database-backup
  workspaces:
    - name: backup
      persistentVolumeClaim:
        claimName: backup
