apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: clean
spec:
  params:
    - name: path
      description: Path to directory being deleted.
      default: '.'
  workspaces:
    - name: source
      mountPath: /workspace

  steps:
    - image: ubuntu
      name: rmdir
      script: |
        #!/usr/bin/env bash
        set -xe

        rm -rf "$(workspaces.source.path)/$(params.path)"
