apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-listener
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: http-event-listener
              servicePort: 8080